// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BLL.DAL;

[Table("BookGenre")]
public partial class BookGenre
{
    [Key]
    public int Id { get; set; }

    public int BookId { get; set; }

    public int GenreId { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("BookGenres")]
    public  Book Book { get; set; }

    [ForeignKey("GenreId")]
    [InverseProperty("BookGenres")]
    public  Genre Genre { get; set; }
}